check for package dependencies including java and asked if you want to install these..

diff --git a/nxt_install b/nxt_install
--- a/nxt_install
+++ b/nxt_install
@@ -10,27 +10,58 @@
 
 export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:";
 
+java_bin=$(which java);
 wget_bin=$(which wget);
 unzip_bin=$(which unzip);
 gpg_bin=$(which gpg);
 shasum_bin=$(which sha256sum);
 
-if [[ -z "$wget_bin" ]] || [[ -z "$unzip_bin" ]] || [[ -z "$gpg_bin" ]] || [[ -z "$shasum_bin" ]]; then
-    echo "Unsatisfied binary dependencies. This script uses the following binarys: wget, unzip, gpg, sha256sum.";
-    echo "These applications must be installed in order to run this script.";
-    exit 1;
-fi
+
+function install_deps {
+
+    if [[ -z "$java_bin" ]] || [[ -z "$wget_bin" ]] || [[ -z "$unzip_bin" ]] ||
+        [[ -z "$gpg_bin" ]] || [[ -z "$shasum_bin" ]]; then
+
+        read -n1 -p "Missing package dependencies, would you like this script to try and install these packages? (y/n): " yesorno
+
+        case "$yesorno" in
+            y) 
+                echo "";
+                apt-get -qq -y update >/dev/null 2>&1 || 
+                { "Error when updating apt package database. Please run apt-get update manually and rerun this script." ; exit 1; }
+                apt-get -qq -y install openjdk-7-jre wget unzip gnupg coreutils >/dev/null 2>&1 ||
+                { echo "Could not install package dependencies, please install these manually and rerun installation script." ; exit 1; }
+
+                return 0;
+            ;;
+
+            n)
+                echo "";
+                echo "Please install package dependencies manually and rerun installation script.";
+                echo "apt-get install openjdk-7-jre wget unzip gnupg coreutils";
+
+                exit 1;
+            ;;
+
+        esac
+
+    fi
+
+}
+
+
 
 function install {
 
 
     if [[ ! -d "/usr/local/bin/nxt/" ]]; then
-    
+
         echo -n "Creating nxt client root directory.. ";
         mkdir -p /usr/local/bin/nxt/ && echo "done." || { echo "Could not create nxt client root directory." ; exit 1;}
     fi
 
     if [[ "$1" != "update" ]] && [[ "$(ls /usr/local/bin/nxt/ |wc -l)" -gt 0 ]]; then
+
         echo "nxt client root directory contain files. If you want to overwrite this, issue an update.";
         exit 0;
     fi
@@ -53,9 +84,11 @@ function install {
 
 
     if [[ -z "$2" ]]; then
+
         client_version=$($wget_bin -q -O -  http://download.nxtcrypto.org | sed 's/\(>\|<\)/ /g' |awk {'print $3 '} | 
                          egrep -v "(e.zip|changelog)" |egrep '(zip$)' |tail -n 1);
     else
+
         client_version=$2;
     fi
    
@@ -70,8 +103,8 @@ function install {
                   egrep $client_version |grep "sha256" |grep "asc")
 
     if [[ -n "$client_sign" ]]; then
-        echo -n "Downloading $client_version shasum signature..";
 
+        echo -n "Downloading $client_version shasum signature..";
         $wget_bin -P /tmp/ -q http://download.nxtcrypto.org/$client_sign > /dev/null 2>&1 || 
         { echo "could not download nxt client shasum signature. Exiting installation." ; exit 1;}
         
@@ -85,15 +118,18 @@ function install {
     sha=$(grep "$client_version" /tmp/$client_sign | awk {'print $1'});
 
     if [[ -n "$sha" ]]; then
+
         echo -n "Verifying $shasum_bin for $client_version..";
         zip_sha=$($shasum_bin /tmp/$client_version |awk {'print $1'});
 
         if [[ "$sha" == "$zip_sha" ]]; then
+
             echo "done."
             $unzip_bin -oq /tmp/$client_version -d /usr/local/bin/ && chown -R nxt:nxt /usr/local/bin/nxt/ > /dev/null 2>&1 ||
             { echo "Could not extract files into nxt client root directory."; exit 1; }
 
         else
+
             echo "CRITICAL: The shasum does not match!. Installation will not continue.";
             exit 1;
         fi
@@ -105,17 +141,20 @@ function install {
 function update {
 
     if [[ -n "$1" ]]; then
+
         asked_version=$1;
         client_version=$($wget_bin -q -O -  http://download.nxtcrypto.org | sed 's/\(>\|<\)/ /g' |awk {'print $3 '} |
                        egrep -v "(*e.zip*|changelog)" |egrep '(zip$)' |grep "$asked_version");
 
         if [[ -z "$client_version" ]]; then
+
             echo "$asked_version does not exist in current location.";
             exit 1;
 
         else
 
             if [[ -f "/etc/init.d/nxtclient" ]] && [[ "$(/etc/init.d/nxtclient status |grep 'started' |wc -l)" -gt 0 ]]; then
+
                 /etc/init.d/nxtclient stop
             fi
 
@@ -126,6 +165,7 @@ function update {
     else
 
         if [[ -f "/etc/init.d/nxtclient" ]] && [[ "$(/etc/init.d/nxtclient status |grep 'started' |wc -l)" -gt 0 ]]; then
+
             /etc/init.d/nxtclient stop
         fi
 
@@ -139,9 +179,18 @@ case "$1" in
 
     install)
         if [[ -n "$2" ]]; then
-            install $2
+
+            if install_deps; then
+
+                install $2
+            fi
+
         else
-            install
+            
+            if install_deps; then
+
+                install
+            fi
         fi
 
         echo "Installation done. Start nxt client with /etc/init.d/nxtclient start, then browse https://localhost:7875";
@@ -150,9 +199,19 @@ case "$1" in
     ;;
     update)
         if [[ -n "$2" ]]; then
-            update $2
+            
+            if install_deps; then
+
+                update $2
+            fi
+
         else
-            update
+ 
+            if install_deps; then
+
+                update
+            fi
+
         fi
 
         echo "Update done.";
