added dynamic paths for wget, unzip, pgp and so on. Made up a new type of licence. THE NXT-WARE LICENSE

diff --git a/nxt_install b/nxt_install
--- a/nxt_install
+++ b/nxt_install
@@ -1,6 +1,12 @@
 #!/usr/bin/env bash
 
-# Post install script for nxt-client
+#  ----------------------------------------------------------------------------
+#  "THE NXT-WARE LICENSE" NXT: 13570469120032392161 (Revision: 25519)
+#  j0b <gemeni@gmail.com> wrote this file. As long as you retain this notice you
+#  can do whatever you want with this stuff. IF you think this stuff is worth it, 
+#  you can send me NXT, my public key is above.
+#  ----------------------------------------------------------------------------
+
 
 export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:";
 
@@ -33,7 +39,7 @@ function install {
     if [[ ! -d "/etc/nxt/" ]]; then
 
         echo -n "Creating configuration directory for nxt client.. ";
-        mkdir -p /etc/nxt && echo "done." || { echo "Could not create nxt client configuration directory." ; exit 1;}
+       mkdir -p /etc/nxt && echo "done." || { echo "Could not create nxt client configuration directory." ; exit 1;}
         cp nxt.conf /etc/nxt/
     fi
 
@@ -47,7 +53,7 @@ function install {
 
 
     if [[ -z "$2" ]]; then
-        client_version=$(wget -q -O -  http://download.nxtcrypto.org | sed 's/\(>\|<\)/ /g' |awk {'print $3 '} | 
+        client_version=$($wget_bin -q -O -  http://download.nxtcrypto.org | sed 's/\(>\|<\)/ /g' |awk {'print $3 '} | 
                          egrep -v "(*e.zip*|changelog)" |egrep '(zip$)' |tail -n 1);
     else
         client_version=$2;
@@ -55,35 +61,35 @@ function install {
    
     echo -n "Downloading $client_version from http://download.nxtcrypto.org..";
     
-    wget -P /tmp/ -q http://download.nxtcrypto.org/$client_version > /dev/null 2>&1 ||
+    $wget_bin -P /tmp/ -q http://download.nxtcrypto.org/$client_version > /dev/null 2>&1 ||
     { echo "could not download nxt client. Exiting installation."; exit 1; }
 
     echo "done.";
 
-    client_sign=$(wget -q -O -  http://download.nxtcrypto.org | sed 's/\(>\|<\)/ /g' |awk {'print $3 '} | 
+    client_sign=$($wget_bin -q -O -  http://download.nxtcrypto.org | sed 's/\(>\|<\)/ /g' |awk {'print $3 '} | 
                   egrep $client_version |grep "sha256" |grep "asc")
 
     if [[ -n "$client_sign" ]]; then
         echo -n "Downloading $client_version shasum signature..";
 
-        wget -P /tmp/ -q http://download.nxtcrypto.org/$client_sign > /dev/null 2>&1 || 
+        $wget_bin -P /tmp/ -q http://download.nxtcrypto.org/$client_sign > /dev/null 2>&1 || 
         { echo "could not download nxt client shasum signature. Exiting installation." ; exit 1;}
         
         echo "done.";
     fi
 
-    gpg --recv-keys 0xFF2A19FA > /dev/null 2>&1 || { echo "Could not recieve public key for file verification. Exiting."; exit 1; }
-    gpg --verify /tmp/$client_sign > /dev/null 2>&1 || { echo "CRITICAL: Failed to verify the file containing sha256sum for nxt client."; exit 1; }
+    $gpg_bin --recv-keys 0xFF2A19FA > /dev/null 2>&1 || { echo "Could not recieve public key for file verification. Exiting."; exit 1; }
+    $gpg_bin --verify /tmp/$client_sign > /dev/null 2>&1 || { echo "CRITICAL: Failed to verify the file containing $shasum_bin for nxt client."; exit 1; }
     cp nxtclient /etc/init.d/ > /dev/null 2>&1 || { echo "Could not copy nxt client init script into /etc/init.d/."; exit 1; }
 
     sha=$(grep "$client_version" /tmp/$client_sign | awk {'print $1'});
 
     if [[ -n "$sha" ]]; then
-        echo -n "Verifying sha256sum for $client_version..";
-        zip_sha=$(sha256sum /tmp/$client_version |awk {'print $1'});
+        echo -n "Verifying $shasum_bin for $client_version..";
+        zip_sha=$($shasum_bin /tmp/$client_version |awk {'print $1'});
         if [[ "$sha" == "$zip_sha" ]]; then
             echo "done."
-            unzip -oq /tmp/$client_version -d /usr/local/bin/ && chown -R nxt:nxt /usr/local/bin/nxt/ > /dev/null 2>&1 ||
+            $unzip_bin -oq /tmp/$client_version -d /usr/local/bin/ && chown -R nxt:nxt /usr/local/bin/nxt/ > /dev/null 2>&1 ||
             { echo "Could not extract files into nxt client root directory."; exit 1; }
         else
             echo "CRITICAL: The shasum does not match!. Installation will not continue.";
@@ -98,7 +104,7 @@ function update {
 
     if [[ -n "$1" ]]; then
         asked_version=$1;
-        client_version=$(wget -q -O -  http://download.nxtcrypto.org | sed 's/\(>\|<\)/ /g' |awk {'print $3 '} |
+        client_version=$($wget_bin -q -O -  http://download.nxtcrypto.org | sed 's/\(>\|<\)/ /g' |awk {'print $3 '} |
                        egrep -v "(*e.zip*|changelog)" |egrep '(zip$)' |grep "$asked_version");
 
         if [[ -z "$client_version" ]]; then
