fixed function for removal of bandwidht limiting.

diff --git a/nxtclient b/nxtclient
--- a/nxtclient
+++ b/nxtclient
@@ -20,14 +20,24 @@ if [[ -z "$pidfile" ]] || [[ -z "$nxtuser" ]] || [[ -z "$javapath" ]]
     exit 0
 fi
 
-function traflimit {
+function disable_traflimit {
 
-    echo "Setting up bandwidth rate limiting...";
+    iprule_exist=$(/sbin/iptables -L OUTPUT -t mangle |grep 'tcp spt:7874 MARK set' |wc -l);
 
-    # Clear up old configuration
+    if [[ $iprule_exist -ge 1 ]]; then
 
-    iptables -D OUTPUT -t mangle -p tcp --sport $limit_port -j MARK --set-mark 10 > /dev/null 2>&1
+        /sbin/iptables -D OUTPUT -t mangle -p tcp --sport $limit_port -j MARK --set-mark 10 > /dev/null 2>&1 ||
+            { echo "Could not remove iptables mangle rule for bandwidht limitation"; return 1; }
+    fi
+
+    # Dont care what tc says, it does not matter, and we do not have to report anything.
     tc qdisc del dev eth0 root > /dev/null 2>&1
+
+    return 0;
+
+}
+
+function traflimit {
 
     # Setup traffic shaping
 
@@ -36,13 +46,11 @@ function traflimit {
     tc class add dev $nxt_int parent 1:0 classid 1:10 htb rate $brate ceil $crate prio 0 >/dev/null 2>&1 ||
         { echo "Failed to set bandwidth rates: $brate, $crate." ; return 1; }
 
-    iptables -A OUTPUT -t mangle -p tcp --sport $limit_port -j MARK --set-mark 10 >/dev/null 2>&1 ||
+    /sbin/iptables -A OUTPUT -t mangle -p tcp --sport $limit_port -j MARK --set-mark 10 >/dev/null 2>&1 ||
         { echo "Failed to add IPTables mangle/package-tagging rule." ; return 1; }
 
     tc filter add dev $nxt_int parent 1:0 prio 0 protocol ip handle 10 fw flowid 1:10 >/dev/null 2>&1 ||
         { echo "Failed to assing traffic limitation rules to appropriate qdisc" ; return 1; }
-    
-    echo "Done." && echo
     
     return 0;
 
@@ -64,7 +72,21 @@ function start {
     done
 
     if [[ "$bwlimit" == "on" ]]; then
-        traflimit
+
+        echo -n "Cleaning up old bandwidht limitation rules...";
+        if disable_traflimit; then
+
+            echo "done.";
+        fi
+
+        echo -n "Configuring bandwidht limitation...";
+        if traflimit; then
+            echo "done.";
+        fi
+
+    else
+
+        disable_traflimit
     fi
 
     status
@@ -85,8 +107,17 @@ function stop {
         done
     fi
 
-    status
-         
+    if [[ "$bwlimit" != "on" ]]; then
+
+        echo -n "Removing bandwidht limitation rules...";
+
+        if disable_traflimit; then
+
+            echo "done.";
+        fi
+    fi
+
+    status     
 
 }
 
